sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: liuning19881117
  alioss:
    access-key-id: LTAI5tKU6g7PK6oyHWp1HaG2
    access-key-secret: 5p45kC5e2XPRFBXIwVLmuAkDj2IzZx
    bucket-name: lunartravel
    endpoint: oss-cn-beijing.aliyuncs.com
